apiVersion: v1
kind: Service
metadata:
  name: foremast-service
  namespace: foremast
  labels:
    app: foremast-service
spec:
  selector:
    app: foremast-service
  ports:
  - port: 8099
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foremast-service
  namespace: foremast
  labels:
    app: foremast-service
spec:
  selector:
    matchLabels:
      app: foremast-service
  template:
    metadata:
      labels:
        app: foremast-service
    spec:
      containers:
      - image: docker.io/foremast/foremast-service:0.0.5
        imagePullPolicy: Always
        name: service
        env:
        - name: ELASTIC_URL
          value: "http://elasticsearch-discovery.foremast.svc.cluster.local:9200/"
        - name: QUERY_SERVICE_ENDPOINT
          value: "http://prometheus-k8s.monitoring.svc.cluster.local:9090/"
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 8099
          name: http
      terminationGracePeriodSeconds: 10
