apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: deploymentmonitors.deployment.foremast.ai
spec:
  group: deployment.foremast.ai
  names:
    kind: DeploymentMonitor
    plural: deploymentmonitors
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            analyst:
              properties:
                endpoint:
                  type: string
                version:
                  type: string
              required:
              - endpoint
              type: object
            autoRollback:
              type: boolean
            logs:
              items:
                properties:
                  filePattern:
                    type: string
                  logName:
                    type: string
                  logType:
                    type: string
                required:
                - logName
                - logType
                type: object
              type: array
            metrics:
              properties:
                dataSourceType:
                  type: string
                endpoint:
                  type: string
                monitoring:
                  items:
                    properties:
                      metricAlias:
                        type: string
                      metricName:
                        type: string
                      metricType:
                        type: string
                    required:
                    - metricName
                    - metricAlias
                    type: object
                  type: array
              required:
              - dataSourceType
              - endpoint
              type: object
            rollbackRevision:
              format: int64
              type: integer
            selector:
              type: object
            startTime:
              type: string
            waitUntil:
              type: string
          type: object
        status:
          properties:
            anomaly:
              properties:
                anomalousMetrics:
                  items:
                    properties:
                      name:
                        type: string
                      tags:
                        type: string
                      values:
                        items:
                          properties:
                            time:
                              format: int64
                              type: integer
                            value:
                              format: double
                              type: number
                          required:
                          - time
                          - value
                          type: object
                        type: array
                    required:
                    - name
                    - values
                    type: object
                  type: array
              type: object
            expired:
              type: boolean
            jobId:
              type: string
            observedGeneration:
              format: int64
              type: integer
            phase:
              type: string
            timestamp:
              type: string
          required:
          - phase
          - timestamp
          - expired
          type: object
      required:
      - spec
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
